### ISSUE TITLE
Wrong bracketing for the bit negation

### ISSUE THREAD

**Issue by CharCoding** [Twilight-Dream-Of-Magic/TDOM-EncryptOrDecryptFile-Reborn#1]
https://github.com/Twilight-Dream-Of-Magic/TDOM-EncryptOrDecryptFile-Reborn/blob/ebfaa28ab895d5ab10e90e9c6f8ee7db8d352e42/include/CommonSecurity/CommonSecurity.hpp#L2013

This does not actually return the negated bits.
Should probably be
`accumulate ^= ~(accumulate << 21);`

**Comment by Twilight-Dream-Of-Magic** [comment]
Oh, thank you！

**Comment by Twilight-Dream-Of-Magic** [comment]
I have actually modified it in a few months.
And verified that your modifications are correct

https://github.com/Twilight-Dream-Of-Magic/TDOM-EncryptOrDecryptFile-Reborn/blob/4405c99c93b976627c5836a0757f59eec9755623/include/CommonSecurity/CommonSecurity.hpp#L2013

In fact I have already told you about it in other chat platforms.
But I feel the need to clarify this matter.
