### ISSUE TITLE
提问：所以，应该怎么使用呢

### ISSUE THREAD

**Issue by Ya2gLu** [Twilight-Dream-Of-Magic/TDOM-EncryptOrDecryptFile-Reborn#4]
请告诉我怎么构建？

**Comment by Twilight-Dream-Of-Magic** [comment]
@Ya2gLu
1. Install a compiler that supports the C++ 2020 standard

Please refer to the repository documentation for details.
Batch script and Shell script
build-project.bat
build-project.sh

2.  Use the CMAKE build tool `cmake CMakeLists.txt` (not this oversimplified command)

CMakeList.txt Files
Multiple Algorithm Encrypting or Decrypting File Reborn Versions - Utility tools
https://github.com/Twilight-Dream-Of-Magic/TDOM-EncryptOrDecryptFile-Reborn/blob/MultiKeyStandardEncipherAndDecipher/CMakeLists.txt

Function Name: OaldresPuzzle-Cryptic
https://github.com/Twilight-Dream-Of-Magic/Algorithm_OaldresPuzzleCryptic/blob/master/OOP/CMakeLists.txt

---

@Ya2gLu
1. 安装支持 C++ 2020 标准的编译器

请详细参考本仓库文件:
Batch脚本和Shell脚本
build-project.bat
build-project.sh

2. 使用CMAKE构建工具`cmake CMakeLists.txt` (不是这个过于简单的命令)

CMakeList.txt Files
多重算法加密或解密文件 - 实用工具
https://github.com/Twilight-Dream-Of-Magic/TDOM-EncryptOrDecryptFile-Reborn/blob/MultiKeyStandardEncipherAndDecipher/CMakeLists.txt

功能名：隐秘的奥尔德雷斯之谜
https://github.com/Twilight-Dream-Of-Magic/Algorithm_OaldresPuzzleCryptic/blob/master/OOP/CMakeLists.txt

**Comment by Ya2gLu** [comment]
👌
